# Generated by Django 6.0.1 on 2026-02-03 09:22

import django.core.validators
import django.db.models.deletion
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board_number",
                    models.CharField(
                        help_text="Уникальный бортовой номер автомобиля",
                        max_length=50,
                        unique=True,
                        verbose_name="Бортовой номер",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("Volvo", "Volvo"),
                            ("Scania", "Scania"),
                            ("MAN", "MAN"),
                            ("Mercedes", "Mercedes"),
                            ("DAF", "DAF"),
                            ("Renault", "Renault"),
                            ("Other", "Другое"),
                        ],
                        default="Other",
                        max_length=50,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Локация"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "ordering": ["board_number"],
            },
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imei",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="IMEI должен содержать 15-20 цифр",
                                regex="^[0-9]{15,20}$",
                            )
                        ],
                        verbose_name="IMEI",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="S/N трекера"
                    ),
                ),
                (
                    "inventory_number_tracker",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Инвентарный номер трекера",
                    ),
                ),
                (
                    "inventory_number_antenna",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Инвентарный номер антенны",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=100, verbose_name="Модель трекера"),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("wialon", "Wialon"),
                            ("galileosky", "GalileoSky"),
                            ("teltonika", "Teltonika"),
                            ("other", "Другое"),
                        ],
                        default="wialon",
                        max_length=50,
                        verbose_name="Протокол",
                    ),
                ),
                (
                    "holder_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Держатель N"
                    ),
                ),
                (
                    "sim_old",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Старый SIM"
                    ),
                ),
                (
                    "n_card",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N Card"
                    ),
                ),
                (
                    "sim_new",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Новый SIM"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Трекер",
                "verbose_name_plural": "Трекеры",
                "ordering": ["serial_number"],
            },
        ),
        migrations.CreateModel(
            name="OrderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to=tracker.models.order_scan_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Скан документа",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        default="Приказ", max_length=100, verbose_name="Тип документа"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Номер документа",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Дата документа")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_documents",
                        to="tracker.car",
                        verbose_name="Автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скан документа",
                "verbose_name_plural": "Сканы документов",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="InstallationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_date", models.DateField(verbose_name="Дата установки")),
                (
                    "removal_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата снятия"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активная установка"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий к установке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="tracker.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="tracker.tracker",
                        verbose_name="Трекер",
                    ),
                ),
            ],
            options={
                "verbose_name": "История установки",
                "verbose_name_plural": "История установок",
                "ordering": ["-installation_date"],
            },
        ),
    ]
