# Generated by Django 6.0.1 on 2026-02-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["state_number"],
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
            },
        ),
        migrations.AddField(
            model_name="car",
            name="state_number",
            field=models.CharField(
                default=1111,
                help_text="Уникальный державний номер автомобиля",
                max_length=50,
                unique=True,
                verbose_name="Державний номер",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="board_number",
            field=models.CharField(
                blank=True,
                help_text="Бортовой номер автомобиля (необязательно)",
                max_length=50,
                null=True,
                verbose_name="Бортовой номер",
            ),
        ),
    ]
