# Generated by Django 6.0.1 on 2026-02-04 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tracker", "0006_alter_car_location_alter_location_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=255, verbose_name="ID объекта"),
                ),
                (
                    "object_repr",
                    models.CharField(
                        max_length=255, verbose_name="Представление объекта"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, null=True, verbose_name="Изменения"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время"),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Путь запроса",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог действий",
                "verbose_name_plural": "Логи действий",
                "ordering": ["-timestamp"],
            },
        ),
    ]
