# Generated by assistant: add order_document FK to InstallationHistory
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationhistory',
            name='order_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='tracker.orderdocument', verbose_name='Приказ'),
        ),
    ]
